version: 1.0

jobs:
  install:
    steps:
      - cd lib/bundlify && npm install && npm run build && npm pack --pack-destination ../
      - npm install
      - npm install --prefix frontend
      - npm install --prefix backend
      - npm install --prefix local-proxy-server

  build:
    steps:
      - npm run build --prefix frontend
      - npm run build --prefix backend
      - npx bundlify

  deploy-api:
    steps:
      - catalyst deploy --only appsail:notification-api

  deploy-proxy:
    steps:
      - catalyst deploy --only appsail:proxy

stages:
  - name: install
    jobs:
      - install

  - name: build
    jobs:
      - build

  - name: deploy
    jobs:
      - deploy-api
      - deploy-proxy
